#!/bin/sh
export XDG_DATA_DIRS=/app/extra/share:/app/share:/usr/share:/usr/share/runtime/share:/run/host/share

# Ensure settings directory exists for Lunacy
SETTINGS_DIR="$HOME/.local/share/Icons8/Lunacy"
if [ ! -d "$SETTINGS_DIR" ]; then
    mkdir -p "$SETTINGS_DIR"
fi

exec /app/extra/Lunacy "$@"
